### ISSUE TITLE
Search does not match all ZIM entries or 'all entry ZIMs' are incomplete

### ISSUE THREAD

**Issue by TiagoSantos81** [kiwix/kiwix-android#1075]
This applies to the 2.4 Build 55. This issue is not described in the issue tracker in any similar form.

**Describe the bug**Tool 
Some words do not appear on the list. I noticed this searching for LanguageTool entry on the Wikipedia-en-nopic.zim from 2017-09-11. Wikipedia dump should have the article, as can be seen in:
https://en.wikipedia.org/w/index.php?title=LanguageTool&action=history

**Expected behavior**
LanguageTool entry appears in the 'Search box' results. The issue may be related to capitalized inner letters in the ZIM index, since 'iPhone' is found, but as 'Iphone'.

**Steps to reproduce the behavior:**
1. Press the 'Search button' in the top panel
2. Click on 'Wikipedia'
3. Type 'LanguageT' (or keep filling in 'LanguageTool')
4. No results are shown in the list

**Environment**
- V2.4 Build 55
- Device : Android Smartphone
- OS version : 'Vanilla' Android 7.0

**Comment by Stevko-sk** [comment]
I can confirm this with v 2.5.1 (2504-kiwix-armeabi-v7a-release.apk downloaded here from GitHub) and with wikipedia_en-all_novid_2018-10.zim.

Entering LanguageTool into search box does not show any results (same when entering it as langaugetool or as Languagetool). The article is contained in zim file: If I open an article that links to it and follow the link, the LanguageTool article is displayed.

This may be related to kiwix/kiwix-lib#196

**Comment by kelson42** [comment]
Quite sure this is fixed with libzim 6.0.0 and Kiwix-Android 3.0, but needs to be confirmed with a recent WPEN ZIM file.

**Comment by macgills** [comment]
Issue still present with Wikipedia 2019-10-21 en nopic, latest develop

**Comment by kelson42** [comment]
@macgills Do we still have this issue?

**Comment by macgills** [comment]
I'll check when we enter 3.5 milestone? Or if anyone else can spare the time to validate

**Comment by kelson42** [comment]
This has been fixed, for sure in 3.7.0
