### ISSUE TITLE
Even after deleting the library downloaded file it still remaining cache

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1126]
Even after deleting the downloaded library file but still remains as the cache file and doesn't get deleted

**Comment by mhutti1** [comment]
Which file specifically are you talking about?

**Comment by gptshubham595** [comment]
like if I downloaded wikitionary  and after deleting that it should be closed and we should be redirected to main page instead even after deleting that file is open and stored in our cache

**Comment by mhutti1** [comment]
Do you have a gif/video of this?

**Comment by gptshubham595** [comment]
Yes wait sending the link
of video

**Comment by gptshubham595** [comment]
[EVEN in cache it remains there](https://vimeo.com/326856188)

**Comment by iadeelzafar** [comment]
I believe this has been fixed in #1346

**Comment by macgills** [comment]
I would think this still exists, when we delete a file that is currently open by ZimContentProvider we need to clear it from that I believe

**Comment by jhbiggs** [comment]
A good issue to work on?

**Comment by kelson42** [comment]
@jhbiggs Definitly if the bug is still there.

**Comment by macgills** [comment]
@jhbiggs are you working on this? If not I will take it over

**Comment by jhbiggs** [comment]
I've been banging my head on it for a while.  Would love to see what you come up with.

**Comment by abdulwd** [comment]
Closed via #1462.
