### ISSUE TITLE
Opening with Kiwix a ZIM file (just after download) from Firefox fails

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3997]
Reproduction steps:
* Going to https://library.kiwix.org
* Downloading a ZIM file
* Clicking on the invitation to "open" the file provided by Firefox
* Choosing to open with Kiwix

I get:
* The library is displayed but the ZIM file is not there

I expect:
* To get an invitation to move/copy the ZIM file to the storage
* Then to display the welcome page of the ZIM

**Comment by kelson42** [comment]
This is not fixed

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Can you please try this APK https://drive.google.com/file/d/1QGad3V-ODFLc0YFsA4Uqmdwl48uZgmQA/view?usp=sharing, and let me know if the problem is fixed or not?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Can you please try with this APK https://drive.google.com/file/d/16uwwoKWdF00rwhvAvR5musunKse4bBwD/view?usp=sharing and let us know that the problem is fixed or not for you?

**Comment by kelson42** [comment]
@kelson42 Still does not work, now Kiwix is not even listed in the list of apps I can open the ZIM file with.
