### ISSUE TITLE
Zoom level option color should be grayed when disabled

### ISSUE THREAD

**Issue by vansh1sh** [kiwix/kiwix-android#556]
**Is it a ?**

- [x] Bug Report

### Step 1: Are you ready to report?
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use :  3.0.1
  * device / operating system :  Samsung J7 / 7.0
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
     When the zoom control switch is disabled the color of the "Zoom level" option should be grayed 
     out, default otherwise.

     When option disabled : 

![image](https://user-images.githubusercontent.com/16793070/36924743-e31bf752-1e95-11e8-8473-b41c39edc7ad.png)

     When option enabled : 

![image](https://user-images.githubusercontent.com/16793070/36924761-eed7e79a-1e95-11e8-949e-c578d953347a.png)
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
     Zoom level option color to be greyed when disabled, else it should be default. 

### Step 4 (optional) : Other Comments:

  * What is the context of this ticket? If not obvious, explain why you need to do this.

    Same color in both the states could cause confusion to the user and would also not give a clear 
    picture about the state of the zoom level option. 
   
Please describe the feature you want to add to the project.

I would like to work on this issue.
@mhutti1 @brijeshshah13 Do let me know what you think.

**Comment by mhutti1** [comment]
Sure go ahead.

**Comment by RishabhRawatAndroid** [comment]
@vansh1sh  where you find the **version 2.3 build 55 **.  I recently clone this repo but I found that my master branch app **version number is 2017-07 build 1** and I have already up to date repo.

**Comment by vansh1sh** [comment]
@RishabhRawatAndroid You need to select the correct build variant. Ensure your build variant is kiwixDebug to build the standard app.

**Comment by RishabhRawatAndroid** [comment]
@vansh1sh  Big thank you vansh1sh.

**Comment by prajurock** [comment]
@mhutti1  Can i work on this issue.If it is not solved.

**Comment by mhutti1** [comment]
Yeah sure If @vansh1sh is no longer working on it.

**Comment by prajurock** [comment]
Okay.I will wait for one day if he don't reply then i will start working.

**Comment by vansh1sh** [comment]
@prajurock I think this issue is resolved and referenced in one my commits earlier. 
Just check once, if not you can go ahead.

**Comment by prajurock** [comment]
@vansh1sh i check the latest version of app.But this issue is still there

**Comment by kelson42** [comment]
@mhutti1 @soloturn Any reason to keep this ticket open?

**Comment by soloturn** [comment]
probably no ... travis failed though now, but, for the pull request itself it did not: https://travis-ci.org/kiwix/kiwix-android/builds/497753402?utm_source=github_status&utm_medium=notification
