### ISSUE TITLE
Searching in Malayalam on Android doesn't work

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-android#816]
Install Kiwix, version 2.2. Install the Malayalam Wikipedia.

Type "ഇന്ദിരാ" in the search box. This is the name "Indira", as in [Indira Gandhi](https://ml.wikipedia.org/wiki/%E0%B4%87%E0%B4%A8%E0%B5%8D%E0%B4%A6%E0%B4%BF%E0%B4%B0%E0%B4%BE_%E0%B4%97%E0%B4%BE%E0%B4%A8%E0%B5%8D%E0%B4%A7%E0%B4%BF). The correct word is seen in the search box, but what actually comes up at the top of search results is not but "ഇന്ദിരാ", but "ഇനദര". In technical terms, only the first part of each Malayalam ligature is shown. (Perhaps @santhoshtr will have a more precise description.)

Tapping this search results doesn't bring up any results, and the app goes back to the home page of the Malayalam Wikipedia.

**Expected behavior**
"ഇന്ദിരാ ഗാന്ധി" must be at the top of the search results, and tapping it must show the Indira Gandhi article ([ഇന്ദിരാ ഗാന്ധി](https://ml.wikipedia.org/wiki/%E0%B4%87%E0%B4%A8%E0%B5%8D%E0%B4%A6%E0%B4%BF%E0%B4%B0%E0%B4%BE_%E0%B4%97%E0%B4%BE%E0%B4%A8%E0%B5%8D%E0%B4%A7%E0%B4%BF)).

**Screenshots**
![malayalam bug](https://user-images.githubusercontent.com/346271/43044270-758766fe-8da3-11e8-960f-65c31eb0dd98.jpg)

**Environment**
- Version of Kiwix Android : 2.2
- Device : Redmi Note 5 Pro
- OS version :  Android 8.1.0 OPM1.171. MIUI Global 9.5

**Comment by viswam** [comment]
Observations:
1. Apparently, the search autosuggest list shows up filtering out all vowels and displaying only the consonant characters within the originally input search word.
2. Regardless of the autosuggestions, the actual search results seems to process the search word properly and the output is as desired normally.

**Comment by mhutti1** [comment]
Its possible this could be a display issue fixed in 2.4

**Comment by kelson42** [comment]
@viswam @amire80 Thank you for your bug report, I have tried wit last version (currently being staged rolling out) and it seems to work fine. See the screenshot. Please reopen the ticket if it still fails with 2.4.

![screenshot](https://user-images.githubusercontent.com/1029718/43365079-35b4224a-9327-11e8-82b2-32f43138fd88.png)

**Comment by viswam** [comment]
I see that my Kiwix version on the mobile is 2.2
When I search in Google's play Market store, my version seems to be the latest (in which, the problem persists).
How can I access ver 2.4?

**Comment by kelson42** [comment]
@viswam It will be updated on your device sometime soon, If you want to check now, you can download a nightly build https://download.kiwix.org/nightly/

**Comment by viswam** [comment]
Thanks. @kelson42 ! :-)   I will look forward and report back. Great day ahead!
